language: ruby
rvm:
  - 2.3.1

before_script:

script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake test
before_script:
    - psql -c "CREATE USER pguser WITH PASSWORD 'pgpass';" -U postgres
    - psql -c 'CREATE DATABASE login_app_test' -U postgres
