language: ruby
rvm:
- 2.3.3
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.example config/database.yml
script:
  - bundle exec rails test
